### ISSUE TITLE
Desktop entry for alsa-scarlett-gui not showing up with nix package manager

### ISSUE THREAD

**Issue by inyourfoss** [SebTM/SebTM#3]
So I have been playing around with nix on Debian Sid + Gnome. 

I installed alsa-scarlett-gui via:
`nix-env --install --attr nixpkgs.alsa-scarlett-gui`

At first none of the packages from nix would show up in the Gnome application overview or when searcching for it. So I added `~/.nix-profile/share/applications` to my XDG_DATA_DIRS environment variable.
And boom they showed up. Only alsa-scarlett-gui would not show up in the Gnome application overview.
Then i noticed the provided desktop enty file `vu.b4.alsa-scarlett-gui.desktop` contained the line:
`Exec=/bin/alsa-scarlett-gui`

But the others had for example:
```
Exec=nvim %F
TryExec=nvim
```
Or something like:
`Exec=/niv/fj03f8f04jf.../veracrypt`

So I changed beforementioned line to the following two lines like with the neovim one:
```
Exec=alsa-scarlett-gui %F
TryExec=alsa-scarlett-gui
```
And Voila it worked!

I hope you can maybe make this small change(or point me to the right direction so that I can submit that change).
I really appreciate you porting this awesome app to nix, because it is not that easy to get otherwise.

I will happily provide further information if needed.

Schöne Grüße aus Unterfranken! :)

**Comment by SebTM** [comment]
Hey @gnumber13,

there shoudn't be any issue - I tested it shortly on latest unstable with sway and after adding it to my config and rebuilding it shows up in rofi which means the desktop-file is recognized in the collection of nixos in the out-directories where it is under `/nix/store/59cb8b539y2r9xccyypyf3lw7qgri4w3-alsa-scarlett-gui-unstable-2022-08-11/share/applications/vu.b4.alsa-scarlett-gui.desktop` (the path before "/share/..." could be different on your system depending on your versions).

I don't use gnome so I might not get to trying it out, and I don't use the tool anymore as I only packaged it to test out if such a device would generally work under NixOS and I don't own one.

You can try to raise an issue at https://github.com/NixOS/nixpkgs/ or if you believe it's a system/config issue ask at [discourse.nixos.org/](https://discourse.nixos.org/) for help, maybe another gnome-user has an idea - I'm happy to adjust the package if there is something reproduce-able to fix - make sure to link this post here ✌🏻

Schöne Grüße aus Bayern :)

**Comment by inyourfoss** [comment]
Hey @SebTM  
so I hacked around a bit and found a solution might not be a perfect one for now. Which i submitted upstream.
Here https://github.com/NixOS/nixpkgs/pull/244024
But it should be reproducible. 

I see you have been asked to review the code.
I cannot 100% verify it will work everywhere but my limited testing showed the patch will be applied to the .desktop file.


Alternatively an inplace sed command could be executed on the .desktop file after installation with the command:
`sed -Ei 's/(Exec\s?=\s?).*/\1alsa-scarlett-gui %F\nTryExec=alsa-scarlett-gui/'  <filename>`


Which changed this file content:
```

[Desktop Entry]

Encoding=UTF-8
Value=1.5
Type=Application
Name=ALSA Scarlett Gen 2/3 Control Panel
Icon=alsa-scarlett-gui
Exec=/bin/alsa-scarlett-gui
Categories=GTK;AudioVideo;Audio;Mixer;
```

To this:

```
[Desktop Entry]

Encoding=UTF-8
Value=1.5
Type=Application
Name=ALSA Scarlett Gen 2/3 Control Panel
Icon=alsa-scarlett-gui
Exec=alsa-scarlett-gui %F
TryExec=alsa-scarlett-gui
Categories=GTK;AudioVideo;Audio;Mixer;
```

**Comment by SebTM** [comment]
Thanks you, I would continue the discussion central for all contributors in the Nixpkgs-MR :)
